url: https://tcsoft.it
baseurl: /

# Site settings
title: TCSoft
email: michal@tcsoft.it
description: "Perfect solutions for your business."


# Team names, titles and social links
people:
- name: Błażej Galiński
  pic: blazej
  position: Software Engineer
  social:
    - title: github
      url: https://github.com/blasius93
    - title: linkedin
      url: https://www.linkedin.com/in/b%C5%82a%C5%BCej-gali%C5%84ski-9a0ab3a7/

- name: Michał Niegrzybowski
  pic: michal
  position: Senior Software Engineer
  social:
    - title: twitter
      url: https://twitter.com/mnie8
    - title: github
      url: https://github.com/mnie
    - title: linkedin
      url: https://www.linkedin.com/in/micha%C5%82-niegrzybowski/

- name: Paweł Kurpierz
  pic: pawel
  position: Business Analyst
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pawe%C5%82-kurpierz-391432142/

- name: Krzysztof Stelmach
  pic: krzysiek
  position: Front-end Developer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/krzysztof-stelmach-463803127/

- name: Łukasz Romanowski
  pic: lukasz
  position: Senior Software Engineer
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/%C5%82ukasz-romanowski-1a36a4190/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/tailored-crafted-software

# Postal address (add as many lines as necessary)
address:
  - line: Gdańsk
  - line: Poland

# Build settings
markdown: kramdown
permalink: pretty