url: https://tcsoft.it
baseurl: /

# Site settings
title: TCSoft
subtitle: Top Code Software
email: michal@tcsoft.it
description: "Perfect solutions for your business."


# Team names, titles and social links
people:
- name: Błażej Galiński
  pic: blazej
  position: Software Engineer
  about: I am a Software Engineer who loves PHP.
  social:
    - title: github
      url: https://github.com/blasius93
    - title: linkedin
      url: https://www.linkedin.com/in/b%C5%82a%C5%BCej-gali%C5%84ski-9a0ab3a7/

- name: Michał Niegrzybowski
  pic: michal
  position: Software Engineer
  about: Software Craftsman with more than 5 years of professional experience who worked as a software engineer, architect, and team leader. Big fan of functional programming, TDD, DDD. Not afraid of any technology or language.
  social:
    - title: twitter
      url: https://twitter.com/mnie8
    - title: github
      url: https://github.com/mnie
    - title: linkedin
      url: https://www.linkedin.com/in/micha%C5%82-niegrzybowski/

- name: Paweł Kurpierz
  pic: pawel
  position: Business Analyst
  about: I am a Business Analyst
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/pawe%C5%82-kurpierz-391432142/

- name: Krzysztof Stelmach
  pic: krzysiek
  position: Front-end Developer
  about:  I have a lot of experience in front-end development. I'm highly skilled in writing code in Javascript, Angular framework, styling in SASS and UX/UI design.
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/krzysztof-stelmach-463803127/

- name: Łukasz Romanowski
  pic: lukasz
  position: Software Engineer
  about: I am a Facebook master
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/%C5%82ukasz-romanowski-1a36a4190/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/top-code-software

# Postal address (add as many lines as necessary)
address:
  - line: Gdańsk
  - line: Poland

# Build settings
markdown: kramdown
permalink: pretty